'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CS2ServerPicker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Beijing___Mobile__China___pekm_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Beijing - Mobile (China) (pekm)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Beijing___Telecom__China___pekt_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Beijing - Telecom (China) (pekt)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Beijing___Unicom__China___peku_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Beijing - Unicom (China) (peku)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Chengdu___Mobile__China___ctum_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Chengdu - Mobile (China) (ctum)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Chengdu___Telecom__China___ctut_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Chengdu - Telecom (China) (ctut)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Chengdu___Unicom__China___ctuu_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Chengdu - Unicom (China) (ctuu)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Shanghai___Mobile__China___pvgm_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Shanghai - Mobile (China) (pvgm)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Shanghai___Telecom__China___pvgt_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Shanghai - Telecom (China) (pvgt)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Shanghai___Unicom__China___pvgu_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Shanghai - Unicom (China) (pvgu)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Shanghai_Alicloud___Mobile__China___pvgm_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Shanghai Alicloud - Mobile (China) (pvgm)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Shanghai_Alicloud___Telecom__China___pvgt_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Shanghai Alicloud - Telecom (China) (pvgt)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alibaba_Cloud_Shanghai_Alicloud___Unicom__China___pvgu_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alibaba Cloud Shanghai Alicloud - Unicom (China) (pvgu)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Amsterdam__Netherlands___ams_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Amsterdam (Netherlands) (ams)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Atlanta__Georgia___atl_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlanta (Georgia) (atl)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Buenos_Aires__Argentina___eze_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buenos Aires (Argentina) (eze)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chennai___Ambattur__India___maa2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chennai - Ambattur (India) (maa2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chicago__Illinois___ord_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chicago (Illinois) (ord)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property China() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("China", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dallas__Texas___dfw_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dallas (Texas) (dfw)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dubai__United_Arab_Emirates___dxb_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dubai (United Arab Emirates) (dxb)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frankfurt__Germany___fra_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frankfurt (Germany) (fra)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GitHub_Mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GitHub-Mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Helsinki__Finland___hel_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Helsinki (Finland) (hel)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hong_Kong__hkg_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hong Kong (hkg)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property India() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("India", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Japan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Japan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Johannesburg__South_Africa___jnb_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Johannesburg (South Africa) (jnb)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lima__Peru___lim_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lima (Peru) (lim)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property London__England___lhr_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("London (England) (lhr)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Los_Angeles__California___lax_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Los Angeles (California) (lax)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Madrid__Spain___mad_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Madrid (Spain) (mad)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Multiplay_Amsterdam__Netherlands___ams4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Multiplay Amsterdam (Netherlands) (ams4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Multiplay_Dallas__Texas___dfw2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Multiplay Dallas (Texas) (dfw2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Multiplay_Hong_Kong__hkg4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Multiplay Hong Kong (hkg4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mumbai__India___bom2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mumbai (India) (bom2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_York__jfk_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New York (jfk)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paris__France___par_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paris (France) (par)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paypal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paypal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World__sha_4__Backbone__Shanghai__China___shb_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World (sha-4) Backbone (Shanghai, China) (shb)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Guangdong_1__China___pwg_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Guangdong 1 (China) (pwg)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Guangdong_2___Mobile__China___canm_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Guangdong 2 - Mobile (China) (canm)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Guangdong_2___Telecom__China___cant_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Guangdong 2 - Telecom (China) (cant)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Guangdong_2___Unicom__China___canu_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Guangdong 2 - Unicom (China) (canu)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Hebei__China___pwu_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Hebei (China) (pwu)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Shanghai___Mobile__China___sham_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Shanghai - Mobile (China) (sham)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Shanghai___Telecom__China___shat_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Shanghai - Telecom (China) (shat)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Shanghai___Unicom__China___shau_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Shanghai - Unicom (China) (shau)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Tianjin___Mobile__China___tsnm_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Tianjin - Mobile (China) (tsnm)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Tianjin___Telecom__China___tsnt_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Tianjin - Telecom (China) (tsnt)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Tianjin___Unicom__China___tsnu_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Tianjin - Unicom (China) (tsnu)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Tianjin__China___pwj_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Tianjin (China) (pwj)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Wuhan__China___pww_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Wuhan (China) (pww)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perfect_World_Zhejiang__China___pwz_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perfect World Zhejiang (China) (pwz)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Santiago__Chile___scl_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Santiago (Chile) (scl)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sao_Paulo__Brazil___gru_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sao Paulo (Brazil) (gru)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seattle__Washington___sea_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seattle (Washington) (sea)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seoul__South_Korea___seo_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seoul (South Korea) (seo)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Singapore__sgp_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Singapore (sgp)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sterling__Virginia___iad_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sterling (Virginia) (iad)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stockholm___Bromma__Sweden___sto2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stockholm - Bromma (Sweden) (sto2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stockholm___Kista__Sweden___sto_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stockholm - Kista (Sweden) (sto)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stockholm__Sweden_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stockholm (Sweden)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sydney__Australia___syd_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sydney (Australia) (syd)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tencent_Guangzhou___Mobile__China___tgdm_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tencent Guangzhou - Mobile (China) (tgdm)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tencent_Guangzhou___Telecom__China___tgdt_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tencent Guangzhou - Telecom (China) (tgdt)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tencent_Guangzhou___Unicom__China___tgdu_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tencent Guangzhou - Unicom (China) (tgdu)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tokyo_Koto_City__Japan___tyo_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tokyo Koto City (Japan) (tyo)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vienna__Austria___vie_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vienna (Austria) (vie)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Warsaw__Poland___waw_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warsaw (Poland) (waw)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
